### ISSUE TITLE
Fetching feature kustomize failed

### ISSUE THREAD

**Issue by stesme** [rio/features#36]
Following feature cannot be installed:
"ghcr.io/rio/features/kustomize:latest": {}

This is in the logs when building the DevContainer mcr.microsoft.com/vscode/devcontainers/base:0-focal

[212155 ms] * Fetching feature: azure-cli_0_oci
[212617 ms] * Fetched feature: azure-cli_0_oci version 1.2.1
[212617 ms] * Fetching feature: dotnet_1_oci
[213063 ms] * Fetched feature: dotnet_1_oci version 1.1.4
[213063 ms] * Fetching feature: kubectl-helm-minikube_2_oci
[213746 ms] * Fetched feature: kubectl-helm-minikube_2_oci version 1.1.4
[213746 ms] * Fetching feature: kustomize_3_oci
[234801 ms] Error getting blob: Error: connect ETIMEDOUT 140.82.121.33:443
[234801 ms] (!) ERR: Failed to fetch feature: Failed to download package for ghcr.io/rio/features/kustomize 
[234801 ms] Error: Failed to download package for ghcr.io/rio/features/kustomize
    at uC (c:\Development\extensions\ms-vscode-remote.remote-containers-0.304.0\dist\spec-node\devContainersSpecCLI.js:285:18414)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async w$ (c:\Development\extensions\ms-vscode-remote.remote-containers-0.304.0\dist\spec-node\devContainersSpecCLI.js:390:10249)
    at async nc (c:\Development\extensions\ms-vscode-remote.remote-containers-0.304.0\dist\spec-node\devContainersSpecCLI.js:390:2538)
    at async gtA (c:\Development\extensions\ms-vscode-remote.remote-containers-0.304.0\dist\spec-node\devContainersSpecCLI.js:611:36050)
[234822 ms] Exit code 1

**Comment by rio** [comment]
This log line indicates it's a networking issue.

> [234801 ms] Error getting blob: Error: connect ETIMEDOUT [140.82.121.33:443](http://140.82.121.33:443/)

Maybe github was having issues? I haven't had issues installing that feature.

**Comment by stesme** [comment]
indeed, and it all started working again an hour ago...
sorry for bothering!
